masterclass:
  title: "Unlocking Productivity with Generative AI: A Practical Introduction for Beginners"
  duration: "One-day masterclass"
  target_audience: "Non-tech-savvy individuals with limited experience in AI"
  
  learning_objectives:
    - "Understand the basics of AI and what makes GenAI different"
    - "Learn about current GenAI tools and their practical applications"
    - "Master fundamental prompt engineering techniques"
    - "Practice advanced prompting strategies for better results"

  key_topics:
    introduction:
      duration: "30 mins"
      focus: 
        - "What is AI and its basic types"
        - "What makes GenAI different"
        - "Real-world examples of AI and GenAI"
        - "Common misconceptions"

    genai_tools:
      duration: "1 hour"
      focus:
        - "Survey of popular GenAI tools"
        - "Tool capabilities and best uses"
        - "Practical applications"
        - "Hands-on demonstrations"

    prompt_engineering:
      duration: "1 hour"
      focus:
        - "Fundamentals of prompt engineering"
        - "Basic prompting techniques"
        - "Interactive exercises"
        - "Best practices"

    advanced_prompting:
      duration: "1 hour"
      focus:
        - "Advanced prompting techniques"
        - "Real-world applications"
        - "Problem-solving strategies"
        - "Practice sessions"

  engagement_methods:
    - "Interactive demonstrations"
    - "Hands-on exercises"
    - "Group discussions"
    - "Real-world examples"
    - "Practice sessions" 