create_initial_outline:
  description: "Based on this masterclass concept: {masterclass_concept}

    Create a detailed course outline that includes:
    - Clear learning objectives for each section
    - Detailed breakdown of topics and subtopics
    - Suggested time allocation for each section
    - Key points to be covered
    - Proposed activities and exercises
    - Assessment methods"
  expected_output: "A detailed course outline in Markdown format"
  agent: content_developer

review_initial_outline:
  description: "Review this initial course outline: {initial_outline}

    Provide detailed feedback on:
    - Alignment with masterclass objectives
    - Content progression and flow
    - Time allocation appropriateness
    - Coverage of key topics
    - Suggested improvements or additions
    - Potential gaps or areas of concern"
  expected_output: "Detailed review and suggestions in Markdown format"
  agent: feedback_agent

create_final_outline:
  description: "Based on the initial outline: {initial_outline}
    And considering this feedback: {outline_review}

    Create the final course outline incorporating the feedback and suggestions.
    Ensure all adjustments maintain alignment with the original masterclass concept: {masterclass_concept}"
  expected_output: "Final course outline in Markdown format"
  output_file: "outputs/final_outline.md"
  agent: content_developer

create_professor_guide:
  description: "Based on the approved course outline: {final_outline}

    Create a comprehensive teaching guide that includes:
    - Detailed explanations for each section
    - Teaching instructions and timing
    - Activities and guidelines
    - Common questions and answers
    - Tips for engagement"
  expected_output: "A comprehensive professor's guide in Markdown format"
  output_file: "outputs/professor_guide.md"
  agent: content_developer

create_presentation_slides:
  description: "Based on the approved course outline: {final_outline}

    Create presentation slides that:
    - Follow the established progression of topics
    - Use concise, non-technical language
    - Include visual elements and interaction points
    - Highlight key concepts and examples"
  expected_output: "Slide-by-slide content in Markdown format"
  output_file: "outputs/slides/presentation_content.md"
  agent: materials_creator

create_student_handout:
  description: "Based on the approved course outline: {final_outline}

    Create a concise reference guide (2-3 pages) that includes:
    - Key concepts and definitions
    - Practical tips and best practices
    - Common pitfalls to avoid
    - Resources for further learning"
  expected_output: "A concise summary document in Markdown format"
  output_file: "outputs/student_handout.md"
  agent: materials_creator

review_all_materials:
  description: "Based on the approved course outline: {final_outline}

    Review all materials to ensure:
    - Alignment with the approved outline
    - Consistency across all documents
    - Appropriate level for the target audience
    - Effective progression of concepts"
  expected_output: "Review report with suggested improvements"
  output_file: "outputs/review/review_report.md"
  agent: feedback_agent