create_initial_outline:
  description: "Create an initial outline for a masterclass with the following concept: {masterclass_concept}. Please provide the outline in {language}."
  expected_output: "A detailed outline in {language} for the masterclass."
  agent: content_developer

review_initial_outline:
  description: "Review this initial course outline: {initial_outline}

    Provide detailed feedback on:
    - Alignment with masterclass objectives and audience
    - Content progression and flow
    - Time allocation appropriateness
    - Coverage of key topics
    - Suggested improvements or additions
    - Potential gaps or areas of concern"
  expected_output: "Detailed review and suggestions in Markdown format"
  agent: feedback_agent

create_final_outline:
  description: "Based on the initial outline: {initial_outline}
    And considering this feedback: {outline_review}

    Create the final course outline incorporating the feedback and suggestions.
    Ensure all adjustments maintain alignment with the original masterclass concept: {masterclass_concept}"
  expected_output: "Final course outline in Markdown format"
  output_file: "outputs/final_outline.md"
  agent: content_developer

create_professor_guide:
  description: "You are creating a comprehensive professor's guide.

APPROVED COURSE OUTLINE:
{approved_outline}

Your task is to create a detailed teaching guide document. You must include:
1. Detailed explanations for each section of the course
2. Step-by-step teaching instructions with timing
3. Specific activities and exercises with implementation guidelines
4. Anticipated student questions and prepared answers
5. Tips for maintaining engagement and handling discussions
6. Additional resources and references for each topic
7. Assessment criteria and grading guidelines

Thought: I will create a comprehensive professor's guide based on the approved outline.
Final Answer: [Your complete professor's guide in markdown format]"
  expected_output: "A comprehensive professor's guide in Markdown format"
  agent: content_developer

create_presentation_slides:
  description: "Based on the approved course outline: {final_outline}
    And using this professor's guide as reference: {professor_guide}

    Create a complete slide deck that aligns with the professor's guide. You must include:
    1. Title slide 
    2. Content slides for each section, following the professor's guide structure. Vary between text and bullet points as seen fit.
    3. Key points and concepts as detailed in the guide
    4. Examples and analogies mentioned in the guide
    5. Interactive elements that complement the guide's activities
    6. Visual element descriptions in details so it can be reproduced by a designer.
    7. Speaker notes that reference the guide's teaching instructions

    Important: Use the professor's guide as your primary reference for content and structure, 
    ensuring the slides support the teaching approach outlined in the guide.

    Format each slide as:
    ## Slide [number]
    Title:[title]
    Content: [content]
    Speaker Notes: [notes from professor's guide]
    Visual Elements: [visual elements description]
    "
  expected_output: "Slide-by-slide content in Markdown format"
  output_file: "outputs/presentation_slides.md"
  agent: materials_creator
  context: [create_professor_guide]

create_student_handout:
  description: "You are creating a student handout.

APPROVED COURSE OUTLINE:
{approved_outline}

Your task is to create a student-friendly reference guide. You must include:
1. Executive summary of the course
2. Key concepts and definitions for each section
3. Practical tips and best practices
4. Common pitfalls and how to avoid them
5. Hands-on exercises and practice problems
6. Resources for further learning
7. Glossary of important terms
8. Note-taking sections

Thought: I will create a student handout based on the approved outline.
Final Answer: [Your complete student handout in markdown format]"
  expected_output: "A concise student handout in Markdown format"
  agent: materials_creator

review_all_materials:
  description: "Based on the approved course outline: {final_outline}

    Review all materials to ensure:
    - Alignment with the approved outline
    - Consistency across all documents
    - Appropriate level for the target audience
    - Effective progression of concepts"
  expected_output: "Review report with suggested improvements"
  output_file: "outputs/review/review_report.md"
  agent: feedback_agent

revise_outline_with_ai_feedback:
  description: "Review and incorporate this AI feedback into the outline:

Original Outline: {initial_outline}

AI Feedback: {ai_feedback}"
  expected_output: "Revised course outline in Markdown format"
  agent: content_developer

revise_outline_with_human_feedback:
  description: "Review and improve this outline: {initial_outline}\n\nHuman feedback: {feedback}\n\nPlease incorporate this feedback thoughtfully and provide a revised version in {language}. Explain your changes briefly at the end."
  expected_output: "A revised outline incorporating the human feedback, with a brief explanation of the changes made."
  agent: content_developer
  context: [create_initial_outline]

revise_with_specialist_feedback:
  description: "Review and improve this outline: {initial_outline}\n\nSpecialist feedback: {feedback}\n\nPlease incorporate the specialist's feedback thoughtfully and provide a revised version in {language}."
  expected_output: "A revised outline incorporating the specialist feedback"

revise_with_human_feedback:
  description: "Review and improve this outline: {current_outline}\n\nHuman feedback: {feedback}\n\nPlease incorporate this feedback thoughtfully and provide a revised version in {language}."
  expected_output: "A revised outline incorporating the human feedback"