design_lesson_plan:
  description: "Design and structure the masterclass lesson plan, including key talking points."
  expected_output: "A comprehensive professor’s guideline in Markdown format."
  agent: content_architect

create_slide_content:
  description: "Develop structured content for each slide of the masterclass in Markdown format."
  expected_output: "Markdown files representing the content for each slide."
  agent: content_architect

draft_reminder_document:
  description: "Draft a concise 2-3 page document summarizing key tools and techniques taught in the masterclass."
  expected_output: "A well-written summary document in Markdown format."
  agent: summary_writer

develop_quizzes_activities:
  description: "Develop interactive quizzes and practical exercises to reinforce learning and engagement."
  expected_output: "Markdown documents containing quizzes and activities tailored to the masterclass content."
  agent: quiz_activity_designer

review_materials:
  description: "Review all materials to ensure clarity, consistency, and alignment with masterclass objectives."
  expected_output: "Feedback and revisions incorporated into the Markdown documents."
  agent: feedback_agent

coordinate_project:
  description: "Oversee the project, manage timelines, and ensure seamless collaboration among all agents."
  expected_output: "A well-coordinated project with all deliverables completed on time."
  agent: coordinator